services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    container_name: app
    environment:
      DATABASE_URL: postgres://bitsaccoserver:${DB_PASSWORD:-password}@postgres:5432/bitsaccoserver
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: bitsaccoserver
      KEYCLOAK_CLIENT_ID: bitsaccoserver-app
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      SERVER_ADDR: 0.0.0.0:5000
    ports:
      - "5000:5000"
      - "5001:5001"  # Hot reload port for development
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    volumes:
      # Development volumes - these are ignored in production
      - ./app:/app/app:${VOLUME_MODE:-delegated}
      - ./entity:/app/entity:${VOLUME_MODE:-delegated}
      - ./migration:/app/migration:${VOLUME_MODE:-delegated}
      - ./Cargo.toml:/app/Cargo.toml:${VOLUME_MODE:-delegated}
      - ./Leptos.toml:/app/Leptos.toml:${VOLUME_MODE:-delegated}
      - ./style:/app/style:${VOLUME_MODE:-delegated}
      - ./public:/app/public:${VOLUME_MODE:-delegated}
      # Cache volumes for development
      - cargo-cache:/app/.cargo
      - target-cache:/app/target
      # Exclude node_modules
      - /app/node_modules
    networks:
      - bitsacconetwork
    tty: true
    stdin_open: true
  
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: bitsaccoserver
      KC_DB_PASSWORD: ${DB_PASSWORD:-password}
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bitsacconetwork

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: bitsaccoserver
      POSTGRES_USER: bitsaccoserver
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - bitsacconetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitsaccoserver -d bitsaccoserver"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  cargo-cache:
  target-cache:

networks:
  bitsacconetwork:
    driver: bridge
