services:
  api:
    container_name: api
    # image: test-api-manual-build
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: bun dev api
    restart: always
    depends_on:
      - postgres
      - swap
    env_file:
      - ./apps/api/.env
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
  swap:
    container_name: swap
    # image: test-swap-manual-build
    build:
      context: .
      dockerfile: ./apps/swap/Dockerfile
      target: development
    command: sh -c "bun prisma migrate deploy --schema apps/swap/prisma/schema.prisma && bun prisma generate --schema apps/swap/prisma/schema.prisma && bun dev swap"
    command: [
        "sh",
        "-c",
        "bun prisma generate --schema apps/swap/prisma/schema.prisma && bun prisma migrate deploy --schema apps/swap/prisma/schema.prisma && bun dev swap"
      ]
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/swap/.env
    ports:
      - '4040:4040'
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=bs
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_datadir:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
volumes:
  postgres_datadir:
