services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      SERVER_ADDR: 0.0.0.0:3030
      # NestJS Backend Configuration
      NESTJS_API_URL: ${NESTJS_API_URL:-http://nestapi:4000/v1}
      API_BACKEND: ${API_BACKEND:-nestjs}
    ports:
      - "3030:3030"
      - "3031:3031"  # Hot reload port for development
    volumes:
      # Development volumes - these are ignored in production
      - ./app:/app/app:${VOLUME_MODE:-delegated}
      - ./Cargo.toml:/app/Cargo.toml:${VOLUME_MODE:-delegated}
      - ./Leptos.toml:/app/Leptos.toml:${VOLUME_MODE:-delegated}
      - ./style:/app/style:${VOLUME_MODE:-delegated}
      - ./public:/app/public:${VOLUME_MODE:-delegated}
      # Cache volumes for development
      - cargo-cache:/app/.cargo
      - target-cache:/app/target
      # Exclude node_modules
      - /app/node_modules
    networks:
      - bitsacconetwork
    tty: true
    stdin_open: true

  nestapi:
    container_name: nestapi
    image: bitsacco/api:main
    env_file:
      - ./.env.nestapi
    depends_on:
      - mongodb
      - fmcd
    ports:
      - '4000:4000'
    restart: always
    networks:
      - bitsacconetwork

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bs
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - mongodb_datadir:/data/db
    restart: always
    networks:
      - bitsacconetwork

  fmcd:
    image: okjodom/fmcd:latest
    container_name: fmcd
    environment:
      - FMCD_DATA_DIR=/data
      - FMCD_ADDR=0.0.0.0:7070
      - FMCD_MODE=rest
      - FMCD_INVITE_CODE=fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75
      # Option A: Auto-generate password (default)
      # Option B: Set explicit password
      # - FMCD_PASSWORD=fmcdpass
      # Option C: Disable auth (dev only)
      # - FMCD_NO_AUTH=true
    ports:
      - 7070:7070
    volumes:
      - fmcd_datadir:/data
    restart: always
    networks:
      - bitsacconetwork

volumes:
  cargo-cache:
  target-cache:
  mongodb_datadir:
  fmcd_datadir:

networks:
  bitsacconetwork:
    driver: bridge
