# Leptos SSR configuration for the admin dashboard

[package]
name = "bitsaccoserver"
version = "0.1.0"

# Required package configuration
lib-package = "app"
bin-package = "app"

# Basic configuration
site-addr = "0.0.0.0:3000"
reload-port = 3001
env = "DEV"

# Output configuration
output-name = "app"
site-root = "target/site"
site-pkg-dir = "pkg"

# Assets
assets-dir = "public"

# SSR Features - server-side rendering only
bin-features = ["ssr"]

# Watch configuration
watch-additional-files = ["style", "public"]
