name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      readme_path:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_REPOSITORY:
        required: true
      DOCKER_HUB_PUBLISH_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Get latest image tag
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        id: get-tag
        run: |
          TAG=$(echo '${{ steps.meta.outputs.tags }}' | head -n1)
          SANITIZED_TAG=$(echo "$TAG" | sed 's/.*\///g')
          echo "tag=$SANITIZED_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PUBLISH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ inputs.dockerfile_path }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update the Docker Hub description
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PUBLISH_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          readme-filepath: ${{ inputs.readme_path }}
