name: publish-server

on:
  push:
    paths:
      - package.json
      - yarn.lock
      - apps/server/**
      - packages/**
      - .github/workflows/publish-server.yml

jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      dockerfile_path: ./apps/server/Dockerfile
      docker_repository: bitsaccoserver-admin
      image_name: server
      readme_path: ./apps/server/README.md
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_HUB_PUBLISH_TOKEN: ${{ secrets.DOCKER_HUB_PUBLISH_TOKEN }}
