//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

// Re-export the enums for external use
pub use super::sea_orm_active_enums::{FedimintOperationType, TransactionStatus};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fedimint_operations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub wallet_id: Uuid,
    pub operation_type: FedimintOperationType,
    pub status: TransactionStatus,
    #[sea_orm(unique)]
    pub fedimint_operation_id: Option<String>,
    pub amount_msat: Option<i64>,
    pub fee_msat: Option<i64>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub request: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub response: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_details: Option<String>,
    pub retry_count: i32,
    pub last_retry_at: Option<DateTimeWithTimeZone>,
    pub processed_at: Option<DateTimeWithTimeZone>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wallets::Entity",
        from = "Column::WalletId",
        to = "super::wallets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wallets,
}

impl Related<super::wallets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
